---
- name: Create Certificate storage directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ acme_storage }}"
    - "{{ cert_storage }}"
- name: Start Caddy
  docker_container:
    name: "{{ inventory_hostname }}_caddy"
    image: wemakeservices/caddy-gen:latest
    state: started
    restart_policy: unless-stopped
    timeout: 120
    volumes:
      - "{{ docker_socket }}:/tmp/docker.sock:ro"
      - "{{ acme_storage }}:/etc/caddy/acme"
      - "{{ cert_storage }}:/etc/caddy/ocsp"
    ports:
      - "80:80"
      - "443:443"
