---
- name: Start Caddy
  docker_container:
    name: "{{ inventory_hostname }}_caddy"
    image: wemakeservices/caddy-gen:latest
    state: started
    restart: yes  # Force a restart to get new config
    # TODO: test recreated vs restarted for config reload
    # recreate: yes
    restart_policy: unless-stopped
    timeout: 120
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs/acme:/etc/caddy/acme
      - ./certs/ocsp:/etc/caddy/ocsp
    ports:
      - "80:80"
      - "443:443"
